import React, { useState } from 'react';

const CORREO_SOPORTE = 'soporte@guajirago.com.co';

const PREGUNTAS = [
  { pregunta: '¿Cómo solicito un taxi o mototaxi?', respuesta: 'Abre GuajiraGo y en la pantalla principal escoge si quieres un Taxi o un Mototaxi. Luego escribe tu punto de origen (dónde estás) y tu destino (a dónde vas). La app te mostrará una tarifa mínima sugerida, que puedes subir si quieres conseguir conductor más rápido. Cuando estés listo, toca "Solicitar" y tu pedido se enviará a todos los conductores cercanos disponibles. En pocos segundos empezarás a recibir respuestas. No tienes que esperar en una sola pantalla: si un conductor acepta tu tarifa o te envía una contraoferta, la app te avisará al instante.' },
  { pregunta: '¿Cómo funciona la negociación de tarifa?', respuesta: 'GuajiraGo usa un sistema justo donde tú decides cuánto quieres pagar. Cuando solicitas un viaje, propones una tarifa inicial. Los conductores cercanos pueden aceptar esa tarifa tal cual, o enviarte una contraoferta con un precio diferente. Verás todas las contraofertas que lleguen, cada una con el nombre del conductor, su foto, placa y vehículo, además de un tiempo límite para responder. Tú eliges la que más te convenga. Si nadie acepta tu oferta inicial, puedes subirla con el botón de "+" para hacerla más atractiva. Este sistema te da el control total sobre lo que pagas.' },
  { pregunta: '¿Qué es el código de seguridad?', respuesta: 'Es una medida de protección para garantizar que subas al vehículo correcto. Cuando solicitas un viaje, GuajiraGo genera automáticamente un código de 4 dígitos basado en tu fecha de nacimiento (día y mes). Este código aparece en tu pantalla cuando el conductor llega a recogerte. Antes de iniciar el viaje, el conductor te pedirá ese código y deberá ingresarlo en su app. Si el código es correcto, el viaje inicia. Esto evita confusiones y asegura que estás subiendo con el conductor que realmente aceptó tu viaje, no con otra persona. Nunca le des tu código a alguien que no sea tu conductor asignado.' },
  { pregunta: '¿Cómo recargo mis créditos?', respuesta: 'Los créditos son necesarios para los conductores, ya que de ahí se descuenta la comisión por cada viaje completado. Para recargar, primero realiza tu pago por Nequi o Daviplata al número oficial de GuajiraGo. Una vez confirmado tu pago, recibirás un código de recarga único. Luego ve al menú, entra a "Mis créditos", escribe ese código en el campo correspondiente y toca "Recargar créditos". Tu saldo se actualizará al instante. Cada código solo se puede usar una vez, así que guárdalo bien hasta que lo apliques.' },
  { pregunta: '¿Qué hago si el conductor no llega?', respuesta: 'Si tu conductor se demora más de lo esperado, lo primero es comunicarte con él. En la pantalla del mapa verás el botón "Llamar al conductor", que te permite hablar directamente con él sin salir de la app ni compartir tu número personal. Pregúntale cuánto falta o si tuvo algún inconveniente. Si no contesta o ves que no va a llegar, puedes cancelar el viaje tocando "Cancelar viaje" y seleccionar la razón. Después podrás solicitar otro conductor de inmediato. Recuerda que también puedes ver su ubicación en tiempo real en el mapa para saber qué tan cerca está.' },
  { pregunta: '¿Puedo cancelar un viaje?', respuesta: 'Sí, puedes cancelar un viaje mientras el conductor todavía va en camino a recogerte. Solo toca "Cancelar viaje" y selecciona el motivo de la lista. Es importante que canceles lo antes posible si cambiaste de opinión, para que el conductor no haga el recorrido en vano. Ten en cuenta que una vez que el viaje ha iniciado (cuando ya subiste al vehículo y el conductor arrancó), no se puede cancelar desde la app. Cancelar de forma responsable y solo cuando es necesario ayuda a mantener un buen servicio para todos.' },
  { pregunta: '¿Qué hago en caso de emergencia durante el viaje?', respuesta: 'Tu seguridad es lo más importante. Durante cualquier viaje, ya sea cuando el conductor va en camino o cuando ya vas rumbo a tu destino, verás un botón rojo de 🚨 Emergencia en la esquina de la pantalla del mapa. Al tocarlo se abre un panel con dos opciones: la primera te permite llamar directamente a la línea de emergencias 123 de Colombia; la segunda comparte por WhatsApp tu ubicación exacta, la ruta de tu viaje y todos los datos del conductor (nombre, foto, placa, color, marca y modelo del vehículo) con tu contacto de confianza. Así, si algo no se siente bien, tus seres queridos sabrán de inmediato dónde estás y con quién.' },
  { pregunta: '¿Por qué no encuentro conductor?', respuesta: 'Hay momentos en que no hay conductores disponibles cerca de tu ubicación, especialmente en horas de baja demanda o en zonas alejadas. Si esto pasa, tienes dos opciones. La primera es subir tu oferta: una tarifa más alta motiva a los conductores a aceptar tu viaje más rápido. La segunda es tocar "Seguir buscando", lo que amplía el radio de búsqueda para incluir conductores que estén un poco más lejos. La app automáticamente amplía la búsqueda con el tiempo. Si después de varios intentos no encuentras conductor, espera unos minutos e intenta de nuevo, ya que constantemente hay conductores conectándose.' },
  { pregunta: '¿Cómo actualizo mi contacto de emergencia?', respuesta: 'Tu contacto de emergencia lo registraste al crear tu cuenta, pero puedes cambiarlo cuando quieras. Ve al menú lateral y entra a la sección "Seguridad". Ahí verás el nombre y número de tu contacto de confianza actual. Toca el botón "Editar" junto al dato que quieras modificar, escribe la nueva información y luego toca "Guardar contacto". Este contacto es la persona a la que se le enviará tu ubicación y los datos del conductor cuando uses el botón de compartir en una emergencia, así que asegúrate de que siempre sea un número correcto y de alguien de tu total confianza.' },
  { pregunta: '¿Cuánto tiempo tengo para salir cuando el conductor llega?', respuesta: 'Cuando tu conductor llega al punto de recogida, se activa un temporizador de espera que puedes ver en tu pantalla. Es importante que salgas lo más pronto posible una vez que el conductor te avise que llegó. Si te demoras demasiado, el conductor tiene la opción de cancelar el viaje, ya que su tiempo también es valioso y puede estar perdiendo otras carreras. Para agilizar el encuentro, usa las respuestas rápidas de la app para avisarle que ya vas saliendo, o llámalo si necesitas darle alguna indicación. Estar listo cuando solicitas el viaje hace que todo sea más rápido para ambos.' },
  { pregunta: '¿Cómo cambio mi contraseña?', respuesta: 'Si olvidaste tu contraseña o quieres cambiarla, ve a la pantalla de inicio de sesión y toca el botón "¿Olvidaste tu contraseña?". Ingresa el correo electrónico con el que te registraste y toca enviar. Recibirás en ese correo un enlace seguro para crear una nueva contraseña. Abre el enlace, escribe tu nueva contraseña y guárdala. Por seguridad, elige una contraseña de al menos 6 caracteres que no sea fácil de adivinar. Si no recibes el correo, revisa tu carpeta de spam o correo no deseado.' },
  { pregunta: '¿Puedo usar GuajiraGo sin internet?', respuesta: 'No, GuajiraGo necesita conexión a internet para funcionar, ya que la app se comunica en tiempo real con los conductores, muestra el mapa y procesa los viajes. Te recomendamos tener datos móviles activos durante todo el viaje, especialmente para poder ver la ubicación del conductor, usar el botón de emergencia y recibir notificaciones. Si tu conexión es inestable, algunas funciones pueden tardar más. Para mejor experiencia, asegúrate de tener buena señal antes de solicitar un viaje.' },
  { pregunta: '¿Cómo actualizo mi foto de perfil?', respuesta: 'Tu foto de perfil ayuda a que conductores y pasajeros se reconozcan. Para cambiarla, abre el menú lateral y entra a "Mi perfil". Toca tu foto actual o el ícono de cámara, y selecciona una nueva imagen desde la galería de tu celular. La foto se guardará automáticamente y aparecerá en tu perfil y en las pantallas de viaje. Te recomendamos usar una foto clara de tu rostro, bien iluminada, para generar más confianza.' },
  { pregunta: '¿Qué pasa si me quedo sin saldo de créditos siendo conductor?', respuesta: 'Como conductor, necesitas créditos para poder recibir y aceptar viajes, ya que de ahí se descuenta la pequeña comisión por cada viaje completado. Si tu saldo baja del mínimo necesario, la app no te permitirá ponerte disponible ni aceptar nuevos viajes, y te mostrará un aviso indicándote que debes recargar. Para seguir trabajando, simplemente recarga tus créditos desde la sección "Mis créditos" usando un código de recarga. Te recomendamos mantener siempre un saldo suficiente para no perder oportunidades de viaje durante tu jornada.' },
  { pregunta: '¿Cómo me registro como conductor?', respuesta: 'Registrarte como conductor es sencillo. Primero crea tu cuenta normal con tus datos personales. Luego, en la pantalla de selección de rol, escoge "Soy conductor". La app te pedirá completar los datos de tu vehículo: el tipo (taxi o mototaxi), la placa, la marca, el modelo, el color, tu número de documento, y deberás subir una foto tuya y una foto de tu cédula. Una vez completados todos estos datos, podrás empezar a recibir solicitudes de viaje. Asegúrate de que toda la información sea correcta, ya que los pasajeros la verán para identificarte.' },
  { pregunta: '¿Qué documentos necesito para ser conductor?', respuesta: 'Para registrarte como conductor en GuajiraGo necesitas tener a la mano: una foto clara de tu rostro (que será tu foto de perfil), una foto de tu cédula de ciudadanía, y los datos completos de tu vehículo, que incluyen la placa, la marca, el modelo (año), y el color. También se te pedirá tu número de documento de identidad. Toda esta información es necesaria para garantizar la seguridad de los pasajeros y para que puedan identificarte correctamente cuando llegues a recogerlos. Mantén tus documentos vigentes y tus datos actualizados.' },
  { pregunta: '¿Qué hago si tengo un problema con un viaje o con un cobro?', respuesta: 'Si tuviste algún inconveniente con un viaje, un cobro de créditos, o cualquier otra situación, puedes comunicarte con nuestro equipo de soporte. Escríbenos al correo soporte@guajirago.com.co explicando tu caso con el mayor detalle posible: incluye la fecha del viaje, el nombre del conductor o pasajero involucrado, y una descripción de lo que pasó. Nuestro equipo revisará tu caso y te dará una respuesta lo antes posible. Tu opinión y tus reportes nos ayudan a mejorar el servicio y a mantener GuajiraGo seguro y confiable para toda la comunidad de Riohacha.' },
  { pregunta: '¿Puedo ser pasajero y conductor al mismo tiempo?', respuesta: 'Sí, con una sola cuenta de GuajiraGo puedes usar ambos roles. Si un día necesitas pedir un viaje como pasajero y otro día quieres trabajar como conductor, puedes cambiar de rol fácilmente desde el menú de la app. Tus datos, tu historial y tus créditos se mantienen en la misma cuenta. Esto es ideal para conductores que también usan el servicio cuando no están trabajando, o para personas que quieren generar ingresos extra manejando en sus tiempos libres.' },
  { pregunta: '¿Cómo califica el pasajero al conductor?', respuesta: 'Al finalizar cada viaje, GuajiraGo muestra automáticamente una pantalla de calificación. Ahí puedes calificar a tu conductor con estrellas (de 1 a 5) según tu experiencia, y dejar un comentario opcional sobre el servicio. Esta calificación es muy importante porque ayuda a mantener la calidad del servicio y permite que otros pasajeros sepan con quién van a viajar. Los conductores también pueden calificar a los pasajeros. Te animamos a calificar con honestidad después de cada viaje, ya que esto mejora la experiencia de toda la comunidad de GuajiraGo.' },
  { pregunta: '¿Puedo guardar mis direcciones favoritas?', respuesta: 'Sí, GuajiraGo te permite guardar hasta 3 lugares favoritos para que no tengas que escribir las direcciones que más usas una y otra vez. Cuando escribas un destino, aparecerá el botón "Guardar este lugar". Al guardarlo, ese lugar quedará disponible como acceso rápido cada vez que vayas a solicitar un viaje. Es perfecto para guardar lugares como tu casa, tu trabajo o la casa de un familiar. Si quieres cambiar uno de tus favoritos, primero borra el que ya no uses tocando la "✕" y luego guarda el nuevo.' },
  { pregunta: '¿Por qué el mapa no carga?', respuesta: 'Si el mapa no aparece o se queda en blanco, generalmente es por uno de estos motivos. Primero, verifica que tienes conexión a internet estable. Segundo, asegúrate de haberle dado permiso a la app para acceder a tu ubicación, ya que el mapa la necesita para mostrarte dónde estás. Si le negaste el permiso, ve a la configuración de tu celular y actívalo para GuajiraGo. Tercero, intenta cerrar completamente la app y volver a abrirla. Si el problema persiste, reinicia tu celular. La mayoría de problemas del mapa se solucionan revisando la conexión y los permisos de ubicación.' },
  { pregunta: '¿Cómo sé que el conductor es de confianza?', respuesta: 'Todos los conductores de GuajiraGo pasan por un proceso de registro donde deben subir su foto personal, una foto de su cédula y los datos completos de su vehículo. Cuando un conductor acepta tu viaje, puedes ver su nombre, foto, placa, color y modelo del vehículo antes de subirte. Además, el código de seguridad de 4 dígitos garantiza que solo subas con el conductor correcto. También puedes ver las calificaciones que otros pasajeros le han dado. Y como medida adicional, siempre puedes compartir los datos del conductor con tu contacto de confianza usando el botón de emergencia. Tu seguridad está respaldada por varias capas de protección.' },
  { pregunta: '¿Qué pasa si el conductor cancela el viaje?', respuesta: 'Si un conductor cancela tu viaje después de haberlo aceptado, recibirás una notificación inmediata en tu pantalla indicándote que el viaje fue cancelado y la razón que dio el conductor. No te preocupes, no se te cobra nada por una cancelación del conductor. Simplemente podrás volver a solicitar un nuevo viaje de inmediato y la app buscará otro conductor disponible para ti. Las cancelaciones de conductores son poco frecuentes, pero pueden ocurrir por motivos como problemas mecánicos o distancia excesiva.' },
  { pregunta: '¿GuajiraGo funciona de noche?', respuesta: 'Sí, GuajiraGo funciona las 24 horas del día, todos los días. Puedes solicitar taxis y mototaxis a cualquier hora. Es importante que sepas que durante la noche, específicamente entre las 6:00 pm y las 6:00 am, la tarifa mínima es un poco más alta que durante el día. Esto se debe a que hay menos conductores disponibles en horario nocturno y para compensar el servicio en esas horas. La diferencia de tarifa es justa y se aplica automáticamente. De noche, te recomendamos especialmente usar el código de seguridad y compartir tu viaje con tu contacto de confianza.' },
  { pregunta: '¿Cómo contacto al conductor antes de que llegue?', respuesta: 'Una vez que tu viaje está confirmado y el conductor va en camino, verás en la pantalla del mapa el botón verde "Llamar al conductor". Al tocarlo, podrás hablar directamente con él a través de la app, sin necesidad de marcar su número ni compartir tu teléfono personal. Esto es útil para darle indicaciones de cómo llegar a tu ubicación exacta, avisarle que ya saliste, o coordinar el punto de encuentro. La llamada es por internet, así que asegúrate de tener buena conexión. Comunicarte con tu conductor hace que el encuentro sea más rápido y fácil.' },
  { pregunta: '¿Puedo pedir un viaje para otra persona?', respuesta: 'Actualmente el viaje se solicita y se gestiona desde tu propia cuenta. Si quieres pedir un viaje para un familiar o amigo, puedes hacerlo, pero ten en cuenta que el código de seguridad estará basado en tus datos, y las notificaciones llegarán a tu celular. La persona deberá estar en el punto de recogida que indiques. Para mayor seguridad, lo ideal es que cada persona use su propia cuenta de GuajiraGo. Estamos evaluando agregar en el futuro una función para pedir viajes a nombre de terceros de forma más completa.' },
  { pregunta: '¿Qué hago si olvidé algo en el vehículo?', respuesta: 'Si dejaste un objeto olvidado en el vehículo, no te preocupes. Puedes contactar al conductor directamente para coordinar la devolución. Su información de contacto aparece en el historial de tu viaje: ve al menú, entra a "Mis viajes", busca el viaje correspondiente y ahí encontrarás los datos del conductor. Te recomendamos contactarlo lo antes posible, apenas notes que olvidaste algo, para aumentar las posibilidades de recuperarlo. Siempre revisa el asiento y el piso del vehículo antes de bajarte, especialmente de noche.' },
  { pregunta: '¿Cómo funciona el botón de compartir ubicación?', respuesta: 'El botón de compartir ubicación es una herramienta de seguridad muy poderosa. Durante el viaje, toca el botón rojo 🚨 Emergencia en la pantalla del mapa, y luego selecciona "Compartir ubicación, ruta e identidad del conductor". Esto abrirá WhatsApp con un mensaje ya preparado que incluye tu ubicación actual en un enlace de mapa, el origen y destino de tu viaje, y todos los datos del conductor: su nombre, foto, placa, color, marca y modelo del vehículo. Ese mensaje se envía a tu contacto de confianza registrado. Así, una persona de tu confianza puede seguir tu viaje en tiempo real y saber exactamente con quién vas.' },
  { pregunta: '¿Puedo cambiar el destino durante el viaje?', respuesta: 'Una vez que el viaje ha iniciado, el destino registrado en la app no se puede modificar. Si necesitas ir a un lugar diferente al que indicaste originalmente, debes hablarlo directamente con el conductor y llegar a un acuerdo con él sobre el nuevo destino y la tarifa adicional si corresponde. Ten en cuenta que el conductor no está obligado a aceptar un cambio de destino. Para evitar inconvenientes, te recomendamos siempre ingresar correctamente tu destino antes de solicitar el viaje. Si cambias mucho de planes, lo mejor es finalizar el viaje actual y solicitar uno nuevo.' },
  { pregunta: '¿Mis datos personales están seguros en GuajiraGo?', respuesta: 'Sí, en GuajiraGo nos tomamos muy en serio la protección de tus datos. Tu información personal, como tu correo, teléfono y fecha de nacimiento, se almacena de forma segura y solo se usa para el funcionamiento del servicio. Tu número de teléfono no se comparte directamente con conductores o pasajeros, por eso las llamadas se hacen a través de la app. Los datos del conductor que ves (foto, placa, vehículo) son para tu seguridad e identificación. Nunca compartimos tu información con terceros para fines publicitarios. Te recomendamos no compartir tu contraseña con nadie y mantener tu cuenta protegida.' },
];

function normalizar(texto) {
  return texto.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

function AyudaSoporte({ onVolver }) {
  const [busqueda, setBusqueda] = useState('');
  const [abierta, setAbierta] = useState(null);

  const q = normalizar(busqueda.trim());
  const filtradas = PREGUNTAS.filter(p =>
    !q || normalizar(p.pregunta).includes(q) || normalizar(p.respuesta).includes(q)
  );

  return (
    <div style={{ backgroundColor: '#141416', minHeight: '100vh', fontFamily: 'Arial, sans-serif' }}>
      <div style={{ background: 'linear-gradient(135deg, #1A1A1E, #2A2A2E)', padding: '24px 20px', position: 'relative', display: 'flex', alignItems: 'center' }}>
        <div onClick={onVolver} style={{ display: 'flex', alignItems: 'center', gap: '4px', background: 'rgba(255,255,255,0.12)', borderRadius: '12px', color: '#FFFFFF', fontSize: '14px', fontWeight: '500', padding: '8px 16px', cursor: 'pointer' }}>
          <span style={{ fontSize: '20px', fontWeight: '900', lineHeight: '1', position: 'relative', top: '-1px' }}>‹</span> Volver
        </div>
        <h2 style={{ color: '#FFFFFF', margin: '0 auto', fontSize: '20px', fontWeight: '900' }}>Ayuda y soporte</h2>
      </div>

      <div style={{ padding: '24px 20px' }}>
        {/* Tarjeta de contacto */}
        <div style={{ background: 'linear-gradient(135deg, #FFCF4D, #FF7A2F, #D6357E)', borderRadius: '20px', padding: '20px', marginBottom: '24px' }}>
          <p style={{ color: '#141416', fontSize: '15px', fontWeight: '900', margin: '0 0 4px' }}>¿Necesitas ayuda?</p>
          <p style={{ color: 'rgba(20,20,22,0.75)', fontSize: '13px', margin: '0 0 14px', lineHeight: '1.4' }}>Escríbenos y te responderemos lo antes posible.</p>
          <a href={`mailto:${CORREO_SOPORTE}`} style={{ display: 'flex', alignItems: 'center', gap: '10px', background: 'rgba(20,20,22,0.85)', borderRadius: '14px', padding: '14px 16px', textDecoration: 'none' }}>
            <span style={{ fontSize: '22px' }}>📧</span>
            <span style={{ color: '#FFFFFF', fontSize: '14px', fontWeight: 'bold' }}>{CORREO_SOPORTE}</span>
          </a>
        </div>

        {/* Buscador */}
        <div style={{ background: '#1A1A1E', borderRadius: '16px', padding: '14px 16px', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '12px', border: '1px solid #2A2A2E' }}>
          <span style={{ fontSize: '20px' }}>🔍</span>
          <input
            value={busqueda}
            onChange={e => setBusqueda(e.target.value)}
            placeholder="Busca tu pregunta..."
            style={{ background: 'none', border: 'none', outline: 'none', color: '#FFFFFF', fontSize: '16px', width: '100%' }}
          />
          {busqueda && <span onClick={() => setBusqueda('')} style={{ color: '#AAAAAA', fontSize: '20px', cursor: 'pointer' }}>✕</span>}
        </div>

        <p style={{ color: '#555', fontSize: '11px', letterSpacing: '3px', margin: '0 0 12px' }}>PREGUNTAS FRECUENTES</p>

        {/* Lista de preguntas (acordeón) */}
        {filtradas.length === 0 && (
          <div style={{ textAlign: 'center', marginTop: '40px' }}>
            <p style={{ fontSize: '50px', margin: '0 0 12px' }}>🤔</p>
            <p style={{ color: '#AAAAAA', fontSize: '14px', margin: '0' }}>No encontramos preguntas con esa palabra.</p>
            <p style={{ color: '#555', fontSize: '13px', margin: '8px 0 0' }}>Escríbenos al correo de soporte y te ayudamos.</p>
          </div>
        )}

        {filtradas.map((p, i) => {
          const estaAbierta = abierta === p.pregunta;
          return (
            <div key={i} style={{ background: '#1A1A1E', borderRadius: '16px', marginBottom: '10px', border: `1px solid ${estaAbierta ? '#FF7A2F' : '#2A2A2E'}`, overflow: 'hidden' }}>
              <div onClick={() => setAbierta(estaAbierta ? null : p.pregunta)} style={{ padding: '16px', display: 'flex', alignItems: 'center', gap: '12px', cursor: 'pointer' }}>
                <span style={{ color: '#FFFFFF', fontSize: '15px', fontWeight: 'bold', flex: 1, lineHeight: '1.4' }}>{p.pregunta}</span>
                <span style={{ color: '#FF7A2F', fontSize: '18px', fontWeight: '900', flexShrink: 0, transform: estaAbierta ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }}>⌄</span>
              </div>
              {estaAbierta && (
                <div style={{ padding: '0 16px 16px' }}>
                  <p style={{ color: '#AAAAAA', fontSize: '14px', margin: '0', lineHeight: '1.6' }}>{p.respuesta}</p>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default AyudaSoporte;